### ISSUE TITLE
Vault Food does not propagate to all raiders

### ISSUE THREAD

**Issue by DDR-Khat** [waidesoper/thevaultstreamer#16]
**Describe the bug**
Eating any items that increase your timer in the vault does not correctly reflect that to other players.

**To Reproduce**
1. Get any vault food, like "Sweet Kiwi"
2. Eat it.
3. ???
4. Sadness

**Expected behavior**
The vault's timer should be updated for all connected clients.

**Screenshots or Crash Report**
N/A

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version [e.g. 1.0.4-streamer2]

**Solution**
You can replace the code of this;
```
            if (!worldIn.isRemote && entityLiving instanceof ServerPlayerEntity) {
                ServerPlayerEntity player = (ServerPlayerEntity) entityLiving;
                VaultRaid raid = VaultRaidData.get((ServerWorld) worldIn).getActiveFor(player);
                raid.ticksLeft += getExtraVaultTicks();
                raid.sTickLeft += this.getExtraVaultTicks();

                player.attackEntityFrom(this.damageSource, 6);

                worldIn.playSound(null,
                        player.getPosX(),
                        player.getPosY(),
                        player.getPosZ(),
                        SoundEvents.BLOCK_CONDUIT_ACTIVATE,
                        SoundCategory.MASTER,
                        1.0F, 1.0F);
            }
```

with this;

            if (!worldIn.isRemote && entityLiving instanceof ServerPlayerEntity) {
                ServerPlayerEntity player = (ServerPlayerEntity) entityLiving;
                List<ServerPlayerEntity> players = new ArrayList<>(player.getServerWorld().getPlayers());
                for(ServerPlayerEntity seek:players)
                {
                    VaultRaid raid = VaultRaidData.get((ServerWorld) worldIn).getActiveFor(seek);
                    raid.ticksLeft += getExtraVaultTicks();
                    raid.sTickLeft += this.getExtraVaultTicks();
                    worldIn.playSound(null,
                            seek.getPosX(),
                            seek.getPosY(),
                            seek.getPosZ(),
                            SoundEvents.BLOCK_CONDUIT_ACTIVATE,
                            SoundCategory.MASTER,
                            1.0F, 1.0F);
                }
                player.attackEntityFrom(this.damageSource, 6);

            }

Note; This is only the Lemon.

**Comment by waidesoper** [comment]
The suggested solution would work, but would also affect players who weren't online when the vault was joined.

**Comment by DDR-Khat** [comment]
It shouldn't effect any players 1) not in the vault 2) not online.
At the time of consumption it seeks the playerlist for the world the player is in - the vault - and this list is only populated by players that are online.

**Comment by waidesoper** [comment]
What happens when you call getRaidData() on a player not in the vault dimension?

**Comment by waidesoper** [comment]
What I mean is: the only way to avoid going to the vault with everyone else logged in, is to log off until the vault is joined, then log on again.

**Comment by DDR-Khat** [comment]
You can work around this particular issue by making it that you seek for all players in the same dimension as the player that activated the vaultportalblock.

**Comment by waidesoper** [comment]
raid.playerIds() contains a list of UUIDs in the current raid. The code just needs to be adjusted to use this list.

**Comment by DDR-Khat** [comment]
If you are referring to the food code, then sure you can do it that way. If you are referring to "giving it to everyone";
I personally would think that the following code is better for the approach for bringing others into a vault;

```
                    if(ModConfigs.VAULT_COOP_ONLY.IS_COOP_ONLY){
                        List<ServerPlayerEntity> players = new ArrayList<>(world.getServer().getPlayerList().getPlayers());
                        players.removeIf(seek -> seek.getServerWorld()!=player.getServerWorld());
                        VaultRaidData.get(destination).startNew(players,Collections.emptyList(), state.get(RARITY), playerBossName, portal.getData(), false);
```

**Comment by waidesoper** [comment]
Is the new line there to check if a player is not online? I'm not sure I understand what it is doing.

**Comment by DDR-Khat** [comment]
If a player is not online, it does not fetch them with getPlayerList() .

**Comment by waidesoper** [comment]
Cool, I will add that.

**Comment by waidesoper** [comment]
for the fruit issue, I can just make it call the syncTicksLeft() method from vaultraid.

**Comment by waidesoper** [comment]
I'm uploading a release for testing

**Comment by DDR-Khat** [comment]
When you do that, if you could also git push your code base. I'd love to see the changes made. As I was trying to get this working for my play group but we were using our own /the_vault internal values.

**Comment by waidesoper** [comment]
should be done now.
