### ISSUE TITLE
co-op mobs don't despawn?

### ISSUE THREAD

**Issue by DDR-Khat** [waidesoper/thevaultstreamer#17]
Your comment in your recent co-op version of 1.0.2-streamer4 states mobs no longer despawn. But I cannot find any changes at all on the git nor in the published source doing anything of the sort - it only mentions adding the option of a config file??

What changes were made?

**Comment by waidesoper** [comment]
I think it's in the release, but the source may have been clawed back while I was trying to clean up - I was asked by the iskallia team to reconsider releasing this, so I took some action to revert the coop-only stuff from the default origin.

Essentially when the code checks if it should respawn a mod more than 24 blocks away, it checks the list of players to see if the mob is within 24 blocks of them too.

**Comment by waidesoper** [comment]
`		List<UUID> playerUUIDs = this.raid.playerIds();
		Boolean removeMob = true;
		this.mobs.removeIf(entity -> {
			for(UUID playerUUID:playerUUIDs){
				ServerPlayerEntity splayer = this.getServer().getPlayerByUUID(playerUUID);
				if(entity.getDistanceSq(splayer) <= 24 * 24) {
					removeMob = false;
				}
			}
			if(removeMob){
				entity.remove();
				return true;
			}
			return false;
		});`

**Comment by DDR-Khat** [comment]
How interesting. You put the same despawn code in that I did but that didn't seem to fix it for me?

**Comment by waidesoper** [comment]
Also, if you're up for some testing. Check out my other project [vaultaddons](https://github.com/waidesoper/vaultaddons/releases).

I'm working on making my work into a separate mod so I can post it on Curseforge with no ramifications from the VH community.

Ultimately, I plan to switch completely over to the separate mod so I'm not babysitting another codebase.

**Comment by DDR-Khat** [comment]
I can confirm that the mobs do not despawn. So your solution does seem to work. Not sure why my implementation didn't work using a similar approach but oh well.
