### ISSUE TITLE
Internal commands should be configurable

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#25]
The values for the internal commands are hard-coded and don't necessarily suit every player's audience. Ideally this should be configurable in a few ways - globally (config file), per player (no idea), or unconfigured (default values)

**Comment by DDR-Khat** [comment]
Making a configuration option for this is easy. And approaching it from a realistic approach it should be a "global" range that is agreed upon by everyone that plans to participate on the server this mod is running on.

**Comment by waidesoper** [comment]
Agreed. We'll add the config.

**Comment by DDR-Khat** [comment]
I've personally being using customised values anyway. So I have a good idea on how to present a config file for this. I'll get it done whilst I'm doing other bits, might as well as I already have the code basically done anyway.

**Comment by DDR-Khat** [comment]
Submitted a pull in regards to this.

**Comment by waidesoper** [comment]
Well done!
