### ISSUE TITLE
Toggle-able effects

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#26]
Mentioned on reddit by u/DaycareJr - 

> In season one it was really hard to build a lot of buildings with the number of extra effects I had, for example, I kept falling off because of the speed. And sometimes you don't need step-up for example in the nether it sometimes bugged a bit and Yeeted me in to the lava.
> 
> Maybe it can be like the ability wheel but than a separate one to toggle them on and off

I think this is something we can achieve

**Comment by DDR-Khat** [comment]
Step-up has a bug in the public release which has been fixed here, this may resolve that particular persons issue.
