### ISSUE TITLE
Better hearts display

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#27]
Suggested on Reddit by https://github.com/Iskallia/Vault-public.git -
`There are some mods that add a better display for health. In endgame half of your screen is hearts, I can imagine in s2 this will be even more with the extra hearts effect on the armor.`

I don't know if this is something we should tackle, but thought I would grab any suggestions from the community.

**Comment by DDR-Khat** [comment]
It's not a bad idea. A common trick that a lot of mods like to do with "extra" health bars is by basically adjusting the colour of the hearts,.
Starting with red (which is default), health "beyond" that would begin to colour the bar in again from the left with a newer colour (green, usually from my experience), then blue. After that I've never seen something reach that many. 

This will however conflict in nature with the "wither" heart colouring.

**Comment by waidesoper** [comment]
Closing this as another mod can do it.
