### ISSUE TITLE
Sub fighters should be emptied after a raid is completed

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#31]
At the moment, the sub fighters list will continue to build up indefinitely. This is obviously not good.

**Comment by DDR-Khat** [comment]
What does the sub fighters *actually* do?

**Comment by waidesoper** [comment]
They are twitch subscribers, they show up as mobs in the vault.

**Comment by DDR-Khat** [comment]
And it should only occur during the -next- vault specifically?

**Comment by waidesoper** [comment]
I think so, I'm not too sure how they manage it in vh but I'm pretty sure I've only seen myself as a sub fighter in one vault after I've subscribed. So it seems plausible that this is what they do.

They are random zombie type mobs that show up in the vault with the subscriber's Minecraft skin, they have random effects applied to them and random equipment. They drop vault dust amongst other normal mob loot.

**Comment by DDR-Khat** [comment]
Mobs do not drop mob loot in the vault, so this is an odd statement.

**Comment by waidesoper** [comment]
Like Vault Bronze.

**Comment by DDR-Khat** [comment]
Do you mean vault gold?

**Comment by waidesoper** [comment]
Haha, yep, been watching too much vh2

**Comment by DDR-Khat** [comment]
No mobs in the vault drop any items. Including vault gold.

**Comment by waidesoper** [comment]
Oh. Maybe I should look at the loot tables before speaking.

**Comment by DDR-Khat** [comment]
Mobs may or may not have loot tables. But if a mob dies within the vault, it's loot drop event is cancelled.

**Comment by waidesoper** [comment]
I've had another look, it appears the list only gets cleared after an arena occurs.

**Comment by DDR-Khat** [comment]
So, I can confirm that the sub fighters do indeed drop items. What might be a smart solution is once they have been spawned for the first time they are removed from the list. That way they show up at least once after having subscribed.

**Comment by waidesoper** [comment]
They certainly drop vault gold. That's the only thing I think they need to drop. I think if we could add a mechanic to let the streamer know when they have hit a threshold in the fighter list, then add a fighter list reset command (which I think we should've added in the first place) that could achieve what we want.

**Comment by waidesoper** [comment]
I just pushed a change that implements this mechanic, I'd love your feedback on it

**Comment by DDR-Khat** [comment]
1) The Sub fighter drops vault diamonds, can confirm from our own play environment.

2) The change you have done seems appropriate enough although it does mean that 100th sub would never appear in a vault, which could be disappointing for the sub themselves.

**Comment by waidesoper** [comment]
I guess so, but at the same time, it's the streamer's choice when to reset the list. Technically they could set the threshold to 1 and get fanfare every sub. 

We could set another option to reset the list after the threshold has been met and a vault has been completed.

**Comment by DDR-Khat** [comment]
You are correct that the user could indeed set it to 1 and get it every sub. That doesn't exactly detract from my statement.

A fast/easy approach is the pseudo code equivalent of;
```
if((Fighters.size()+1)>=ConfigThreshold)
{
//Do thing! purge list!
}
//Add person to the new list.
```

**Comment by waidesoper** [comment]
Oh,  I meant, the current code doesn't purge the list. You have to type a separate command for that

**Comment by DDR-Khat** [comment]
I thought your previous changes were an attempt to automate the purge process? That's what the code suggested it did at a glance.

**Comment by waidesoper** [comment]
So the internal command plays fanfare when you meet or exceed the threshold. You need to use the reset_fighters command to clear the list

**Comment by DDR-Khat** [comment]
Right. If you already have the code recognising this configured threshold, why not have the threshold purge the list at that time? (Or even provide a configuration option to do this)

**Comment by waidesoper** [comment]
I didn't think it fully through to be honest.

**Comment by waidesoper** [comment]
The thing is, you have a list of 100 people, preferably you'd want to draw a name out of that list to get your arena champion. VH do this by simulating the arena. I don't think we are at a stage where we could (or should) pull that off, but I think we should use that list to do a random draw, so that the arena champion can be selected and the arena crate can be awarded.

Should we, instead of immediately purging the list, randomly select a username from the list and either display it on screen or give it straight to the streamer? After that we could purge the list, or wait until the next vault is completed.

**Comment by DDR-Khat** [comment]
That sounds like a perfect reason for the configuration option to me.

ImmediateArenaPurge <True/False>

**Comment by waidesoper** [comment]
I've had a go, here's what I came up with

- implemented your pseudo-code
- added a purgemode to vault fighters config with 3 options - manual, threshold, raid
- manual does nothing
- threshold runs your code
- raid clears the list at the end of a raid (too bad about subs during the raid)

**Comment by waidesoper** [comment]
Can you think up a clean way to select the arena champion? We can add it to the threshold mode. I'm not too good with the random stuff.

**Comment by waidesoper** [comment]
A random selection would be fine, but wouldn't it be nice to take into account the tier and length of the sub to add a weight so that higher tier subs get a better chance at winning? 

Theoretically, this more closely mimics the arena, as the higher tier, and longer term subs have a higher chance because they are bigger and get better chance of decent weapons and armour.

**Comment by waidesoper** [comment]
I think this needs more work. But it is in the latest release so I suppose getting some feedback would help guide future decisions.
