### ISSUE TITLE
Need to add config examples to readme or release

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#34]
With the plethora of config options that we have made available we now need to tell our users how to use them. We can always add the info to the Readme, but I think adding them to the release we should be able to ease transitions.

**Comment by DuskyShip260** [comment]
I have created a wiki at [this fork of the repository](https://github.com/DuskyShip260/thevaultstreamer/wiki). You can add these to the wiki of this repository if you would like.

**Comment by waidesoper** [comment]
That's beautiful. There's a couple of items I can give you some insight on. Should I make an issue on your fork?

**Comment by waidesoper** [comment]
Would you like to join our Discord - https://discord.gg/QD9kvnFuA4

**Comment by DuskyShip260** [comment]
You can either make an issue on the repository or edit the wiki directly.

**Comment by waidesoper** [comment]
Resolved by DuskyShip260
