### ISSUE TITLE
Crash on World Join/World Creation

### ISSUE THREAD

**Issue by VIPT0xic** [waidesoper/thevaultstreamer#37]
Game/Server Crashing on joining of player, when joining server, the player joining doesnt crash but the server does.

**To Reproduce**
1. Start up game
2. Join Server/Create World
3. Crash

[crash-2021-06-10_15.55.04-server.txt](https://github.com/waidesoper/thevaultstreamer/files/6632620/crash-2021-06-10_15.55.04-server.txt)

- Both, Single-Player+Server
- 1.0.6.1-streamer

**Additional context**

**Comment by waidesoper** [comment]
Does this happen for all players on the server?

**Comment by waidesoper** [comment]
I can't see any reason in the code that you would be getting this error unless you are already in the vault. So I've pushed a release that should fix that. Try updating to [1.0.6.2-Streamer1](https://github.com/waidesoper/thevaultstreamer/releases/tag/1.0.6.2-Streamer1)

**Comment by DDR-Khat** [comment]
The reason for the code failure is they are running a raid that was generated from a prior version of The streamer version of the_vault.
```iskallia.vault.world.raid.VaultSpawner.lambda$tick$0(VaultSpawner.java:46)```
which is;
```for (ServerPlayerEntity splayer : players) {```

So the raid is attempting to iterate over players that are in the vault, but the particular vault they are running was initialised without this data as it was introduced in 1.0.5-streamer.

The vault needs to be finished in that version before they will be able to exit.

**Comment by VIPT0xic** [comment]
That was the issue!
