### ISSUE TITLE
Raffle vault boss is just Robot with a name

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#39]
For some reason the boss in a raffle vault is just the robot entity with the playerbossname instead of the actual Minecraft player

**Comment by MeinKraft** [comment]
is this just a reminder to yourself or would you like some help with this?

**Comment by waidesoper** [comment]
Anyone can have a go. I'd love some help with it

**Comment by MeinKraft** [comment]
from line 96 in ObeliskBlock.java class, add this code and it should work - I did test it

```Java
//        if(type == EntityScaler.Type.BOSS) {
//            boss = ModConfigs.VAULT_MOBS.getForLevel(raid.level).BOSS_POOL.getRandom(world.getRandom()).create(world);
//        } else {
//            return;
//        }


        // #Crimson_Fluff, if crystal has a boss name then summon textured fighter
        if (type == EntityScaler.Type.BOSS) {
            if (! raid.playerBossName.isEmpty()) {
                boss = ModEntities.VAULT_FIGHTER.create(world);
                boss.setCustomName(new StringTextComponent(raid.playerBossName));
            }
            else if (ModConfigs.VAULT_MOBS.getForLevel(raid.level).BOSS_POOL.size() != 0)        // #Crimson_Fluff, just in case
                boss = ModConfigs.VAULT_MOBS.getForLevel(raid.level).BOSS_POOL.getRandom(world.getRandom()).create(world);

            else
                return;
        } else
            return;

```

Also I have a fork with a few updates to it: https://github.com/MeinKraft/Vault-public

**Comment by waidesoper** [comment]
Nice, thanks mate!

**Comment by MeinKraft** [comment]
Ive noticed that you shouldnt need this line ```boss.setCustomName(new StringTextComponent(raid.playerBossName));```
as there is a setCustomName call at the bottom of that method

this will need testing just to make sure as I use ``` if (! raid.playerBossName.isEmpty())``` and the code uses ``` if ( raid.playerBossName != null)```

it just cleans the code up by not having 2 calls to setCustomName
