### ISSUE TITLE
Internal command "received_sub" gives error when run.

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#40]
**Describe the bug**
When running `/the_vault internal received_sub DuskyShip260 1 12`, the command results in an "unexpected error." When hovering over the chat message, it shows the error "java.lang.UnsupportedOperationException"

**To Reproduce**
1. run `/the_vault internal received_sub DuskyShip260 1 12`

**Expected behavior**
The actor is added to the pool of sub fighters, and if Tier 3, given a Trader Core.

**Screenshots or Crash Report**
![Recieved_SubError](https://user-images.githubusercontent.com/81256865/122122819-4ac76900-cdfb-11eb-9add-6b03e50af651.png)

**Info (please complete the following information):**
- World Type: Singleplayer
- The_Vault Version 1.0.6.3

**Comment by waidesoper** [comment]
Do you have the vault_streamer_config.json file in your config folder?

**Comment by DuskyShip260** [comment]
I made a new instance and the commands now work correctly. When SUBS_GIVE_TRADER is set to true in config, traders are given for all subs, not just tier 3. I'm not sure if this is intentional or unintentional. If unintentional, I can make a new Issue.

This does not apply specifically to this issue, but some arena dimension generation is still present. The dimension is still present along with the structure generation (main/java/iskallia/vault/world/gen/structure). I'm not completely sure but I think the dimension needs a JSON File for it alongside the JSON File for The Vault dimension. (main/resources/data/the_vault/dimension and main/resources/data/the_vault/dimension_type).

**Comment by waidesoper** [comment]
It's not that it's not intentional - according to the wiki, traders are not given for subs, only gifted subs, so this implementation is our own interpretation on what that would do. By all means create a new issue with your suggestion, I have a few ideas about how we could approach this.

**Comment by DDR-Khat** [comment]
> I made a new instance and the commands now work correctly. When SUBS_GIVE_TRADER is set to true in config, traders are given for all subs, not just tier 3. I'm not sure if this is intentional or unintentional. If unintentional, I can make a new Issue.
> 
> This does not apply specifically to this issue, but some arena dimension generation is still present. The dimension is still present along with the structure generation (main/java/iskallia/vault/world/gen/structure). I'm not completely sure but I think the dimension needs a JSON File for it alongside the JSON File for The Vault dimension. (main/resources/data/the_vault/dimension and main/resources/data/the_vault/dimension_type).

For smaller streamers I felt it fair to allow them to the ability to configure this version of the mod how they see fit, including allowing subs of any amount reward the streamer with a trader -- it's them deciding how they are having fun.

Although I do suppose you are correct that I did not provide bracketing for only enabling tier3 subs like I have done with the BIT and DONOR bracketing so that was perhaps an oversight on my part. It wouldn't be too difficult to make this configurable although I feel it a bit rude to acknowledge a sub but also say "it's not enough" to get a trader. That could be my background as a smaller streamer though.

**Comment by waidesoper** [comment]
My thoughts are that it is good for now.

It's unique like all the other methods of viewer interaction, and gives direct rewards for subs, which I always felt was a bit of a disappointment on the VH streams.
