### ISSUE TITLE
The compiled code is coming out twice the size expected for some reason

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#42]
I just noticed that the compiled mod is coming out at 60MB when it used to only be 25ish. It's odd considering the small amount of code that has been added.

**Comment by MeinKraft** [comment]
compiling what you had on github yesterday with the code change I made, I get 22mb when compiled

try optimizing all your imports, or open the jar and see where the largest files are?

**Comment by MeinKraft** [comment]
just of interest do you guys have a discord?  it would be nice to have somewhere to share ideas and code on related projects

I have a new discord with a channel for Vault Hunters.  Im also working on a 1.16.5 version of VH with bug fixes etc.  I will also be re-working the mod pack and trying to make it playable

You guys are welcome to join (its only 3 days old, lol)

**Comment by waidesoper** [comment]
Could you post the link? I know I'd love to have a way to communicate with other unofficial VH developers

**Comment by MeinKraft** [comment]
https://discord.gg/QD9kvnFuA4

**Comment by waidesoper** [comment]
Fixed - I had work from the_vault_stripped in my working folder which doubled the size
