### ISSUE TITLE
Alias Command only works for Opped Players

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#43]
**Describe the bug**
Players that do not have operator permissions are unable to run `/the_vault alias`

**To Reproduce**
1. deop yourself if already opped
2. try to run `/the_vault alias`

**Expected behavior**
The Player can run the command and set an alias for a player.

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.0.6.7

**Comment by waidesoper** [comment]
Fixed with latest release
