### ISSUE TITLE
Config for Vault Gear Level

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#46]
**PROBLEM**
In VH1, the minimum level Vault Gear can roll is Level 80. While this is somewhat balanced for the original VH streamers (based on the XP earned from subs), this goal is often not realistic for smaller streamers and players using this mod for co-op vaults. This is one balance change left out by the Dev Team prior to public release.
**SUGGESTED SOLUTION**
Add a Minimum and Maximum level roll to vault_gear_base.json or vault_gear.json in config which allows players to configure and balance the vault gear level rolls based on their audience size or if they are playing without using the integration.

**Comment by waidesoper** [comment]
I'll look at this today

**Comment by waidesoper** [comment]
So, in the vault_gear_RARITY files, there are already options for GEAR_LEVEL_CHANCE, GEAR_MAX_LEVEL, and MIN_VAULT_LEVEL. I think this already achieves what you are asking for.
