### ISSUE TITLE
Crash in single player if they leave the game during raid

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#49]
I'm getting a crash if I leave the game during a raid in single player. It's something to do with the mob culling code but I haven't yet worked out what.

**Comment by MeinKraft** [comment]
line: 44 of VaultSpawner, the players variable is null
but the raid.playerIDS is not, so best to iterate through that

or find a way to re-set players upon world load

**Comment by MeinKraft** [comment]
or just save the/load the players into the nbt data in VaultRaid class

**Comment by MeinKraft** [comment]
try this PR  Temp Dim exit/re-enter fix #51
