### ISSUE TITLE
Coop Vaults

### ISSUE THREAD

**Issue by Ruinzxyt** [waidesoper/thevaultstreamer#54]
Vaults can either be only ran as coop only or solo. I tried to add in the config options for the coop modes to see if it would work like it did in previous updates, but to no avail. I even tried to rename the_vault config file so it could re-create a new config file for it. With the new file, the new option for "Coop Modes" still had not been written into config file, although the "Coop only" config file had still been re-created.

I installed the vault version 1.0.7.2 and it no longer worked properly. 

We joined the raiding party, as configs were set to be in the "basic" coop mode, yet it only took the one person that created the vault.

- World Type: Server
- The_Vault Version 1.0.7.2

**Comment by waidesoper** [comment]
Could you post the coop only config please

**Comment by waidesoper** [comment]
Coop mode needs the first option set to true. This is unfortunately a legacy name, seeing this to true enables coop modes

**Comment by Ruinzxyt** [comment]
I just tried to do so and still have the same issue with going into a vault without joining the raiding party and everyone was still pulled in.

**Comment by waidesoper** [comment]
Have you set "COOP_MODE":"basic"?

**Comment by waidesoper** [comment]
You need both options for the Raiders team to work

**Comment by Ruinzxyt** [comment]
Yes. I had tested all the modes earlier this week, I thought I was going crazy. What is the config file supposed to look like entirely for the Streamer config file? Would the command order affect it?

**Comment by waidesoper** [comment]
Hmmmm, try set coop_mode to 1. I might've goofed

**Comment by Ruinzxyt** [comment]
I am still having the issue sadly.

**Comment by waidesoper** [comment]
Thanks for your patience. I think I know the cause so it should be a pretty quick fix but I won't be able to do it for a few hours. I would suggest for the moment that if your want to use coop, just log out the players you don't want in the vault when entering

**Comment by Ruinzxyt** [comment]
Will do no worries, i  honestly thought for about 2 weeks that I messed up the configs or something. lol thank you for the effort you're putting in to making this experience more enjoyable though! Loving the work you've done!

**Comment by waidesoper** [comment]
Can you try the latest release 1.0.7.4-Streamer1  and see if that works.

**Comment by Ruinzxyt** [comment]
The fix works, thank you!
