### ISSUE TITLE
Mob Spawning in Vaults

### ISSUE THREAD

**Issue by Ruinzxyt** [waidesoper/thevaultstreamer#57]
I am having an issue where mob spawning in the vaults work fine when I first get in the vault but as I get out of the portal room mobs don't seem to randomly spawn except for around mob spawners. Mobs just don't seem to spawn and it makes vaults very easy due to that.

Sadly I am not too sure when it started, but I belive it may have started around the time i ported my LAN world to my server.

- World Type: Single Player, turned to LAN then to Server (Same world just moved to each type)
- The_Vault Version 1.0.7.4

Seems to happen to every player as well as in both coop and single player raffle &/or regular vaults.

**Comment by waidesoper** [comment]
In your vault_mobs.json file, what is MAX_MOBS set to?

**Comment by waidesoper** [comment]
I'm looking through the code, here are the points to consider with mobs spawning:

- Mobs more than 24 blocks from any player will despawn
- Mobs will spawn on only on valid spawning spaces (2 non suffocating blocks on top of a spawnable block) in a 56 block wide 40 block high rectangle around the player
- If there are less mobs currently spawned in the vault than the max mobs setting (excluding mobs spawned from a spawner) vaultspawner will randomly select valid spawning spaces, randomly select a mob from the levelled mob pool and try to spawn 
- The size of a vault room is 56*56*40, so if you are in the middle of a vault room, mobs should be able to spawn all the way around you

**Comment by Ruinzxyt** [comment]
Oh, it's set to 3. What should it be at?

**Comment by waidesoper** [comment]
Yeah, that seems normal. It's scaled to your vault level (you should see "MAX_MOBS" for all the level ranges). The maximum in the config is 6, make it like 50 if you want to check that the vault spawner is working properly

**Comment by Ruinzxyt** [comment]
So after a few vaults I tested, even with the increased number of max mobs, it still slows down the mob spawning throughout the vault. it seemed as though it was working in the beginning but then I waited in a room farther away from the portal room and barely any mobs were spawning or none at all would spawn. I tried deleting my vault mobs config folder to get a brand new one 
 on server startup in case I messed something else up and I am still getting the issue.

**Comment by Ruinzxyt** [comment]
ok I goofed it's fine with the 50 as I go through the vaults but even with as high as 6 it slowed down throughout the vault. which is  a bit odd.

**Comment by Ruinzxyt** [comment]
New Info!
It seems to be some how tied to my survival gamemode. When I am in creative travelling through the vaults everything is working fine, the mobs keep spawning properly, but the minute I switch to survival the spawning slows again. 
I am level 33. I do see a difference in being slower spawns than when I first started playing.

**Comment by waidesoper** [comment]
That is interesting, let me see what I can see with that in mind

**Comment by waidesoper** [comment]
This issue should be resolved in release 1.0.8.1
