### ISSUE TITLE
Internal Command for Gift Bombs does not give correct Gift Bomb

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#6]
**Describe the bug**
In the final stream of Vault Hunter's S1 When iskall runs` /the_vault internal received_sub_gift <actor> <amount> <tier>`, the 'tier' integer is used to show the Twitch subscription tier, not the tier of the gift bomb.

**To Reproduce**
1. Run `/the_vault internal received_sub_gift <actor> 100 1` as an Operator

**Expected behavior**
The command should give an Omega Gift Bomb with 100 Subscribers at Subscription Tier 1.

**Info:**
- World Type: Singleplayer
- The_Vault Version 1.0.3

**Comment by waidesoper** [comment]
I see where I went wrong here, do we know what the criteria are for the different levels of gift bomb?

**Comment by waidesoper** [comment]
Found the wiki entry, adding the corrections now

**Comment by waidesoper** [comment]
I've changed the criteria so it matches the wiki.
