### ISSUE TITLE
VH2 Oblisk Mode can allow for multiple bosses per Vault.

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#66]
**Describe the bug**
If one additional obelisk is activated after/during a boss fight, another boss will spawn.
**To Reproduce**
1. Activate the required amount of Obelisks to summon the boss
2. Kill the Boss
3. Activate an additional Obelisk

**Expected behavior**
Only one boss can spawn per vault

**Info (please complete the following information):**
- World Type: Singleplayer
- The_Vault Version 1.0.7.4

**Comment by MeinKraft** [comment]
@DuskyShip260  join the discord for progress/ideas etc

@waidesoper fixed
