### ISSUE TITLE
Reaching required subs to trigger an arena does not give a boss crate.

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#71]
**Describe the bug**
When MAX_FIGHTERS is reached, the arena sound and particles play, but the player is not given an arena crate and the count is not cleared.

**To Reproduce**
1. Set MAX_FIGHTERS to a low number (like 3) to make testing easier
2. Run the `received_sub` command as many times as MAX_FIGHTERS
3. Observe that the player sees the particles and hears the sound, but gets no crate.
4. Run the `received_sub` command again, and see the same result, showing that the list is not cleared.

**Expected behavior**
The player receives a crate, and the list is cleared.

**Info (please complete the following information):**
- World Type: Singleplayer
- The_Vault Version 1.0.7.4

**Additional Info**
Is there a way to display a count of the subs to see if it's a problem with clearing the fighter list?

**Comment by waidesoper** [comment]
What is PURGE_MODE set to

**Comment by MeinKraft** [comment]
I do think there is a bug there in that it doesnt use the new client side subscribers list

**Comment by DuskyShip260** [comment]
The vault_fighters.json file is completely empty except for FIGHTER_LIST. PURGE_MODE isn't in the file. I can try adding it to the file and I'll see what happens.

    {
      "FIGHTER_LIST": []
    }

**Comment by DuskyShip260** [comment]
Adding `"PURGE_MODE": "THRESHOLD"` to the file does not fix the bug.

**Comment by waidesoper** [comment]
Okay, our next release shall have the fix for this

**Comment by DuskyShip260** [comment]
Fixed in 1.0.7.5
