### ISSUE TITLE
Next Release todo list

### ISSUE THREAD

**Issue by waidesoper** [waidesoper/thevaultstreamer#72]
Here's all the stuff we need to do

**Comment by MeinKraft** [comment]
- [ ] Move high-end loot into treasure/extra treasure loot tables

**Comment by waidesoper** [comment]
I'm not sure I'm willing to modify the loot table of the boss crates, we've already made them configurable

**Comment by MeinKraft** [comment]
I meant we could just add a generate call from the common loot or something.

The loot looked a bit bare, but then I didnt test in modpack mode, just the dev environment with all the mods missing

**Comment by waidesoper** [comment]
Treasure room doors - should I a) turn them into structures and use jigsaws to attach them, or b) restore the previous functionality?

**Comment by MeinKraft** [comment]
I would try jigsaws,  weve practically eliminated lag by removing the bedrock/wool placeholders. so it should be worth it

**Comment by waidesoper** [comment]
agreed

**Comment by waidesoper** [comment]
placing the doors in the overworld deletes them...

**Comment by waidesoper** [comment]
how sure are we that luck isn't affecting the drops from crates?

**Comment by MeinKraft** [comment]
extremely sure, as generateLoot or whatever its called from vanilla uses luck in its structure
We dont use generateLoot, our generate does not reference luck or modifier treasure in any way

guess we should change that....

**Comment by waidesoper** [comment]
I think we could technically release now
