### ISSUE TITLE
Internal Command received_bit_donation does not give Trader at 2500 Bits ($25) and 10000 Bits ($100)

### ISSUE THREAD

**Issue by DuskyShip260** [waidesoper/thevaultstreamer#9]
**Describe the bug**
When running `/the_vault internal received_bit_donation 2500`, the user does not receive a trader core
When running `/the_vault internal received_bit_donation 10000`, the user does not receive a Megahead Trader Core

**To Reproduce**
1. Run the command `/the_vault internal received_bit_donation <amount>` with amount being 2500-9999 or 10000+

**Expected behavior**
When amount is in the range 2500 to 9999, The user receives a Trader Core based on a needed command parameter, actor.
When amount == 10000, The user receives a Trader Core based on an actor parameter.

**Info (please complete the following information):**
- World Type: Singleplayer
- The_Vault Version 1.0.3-streamer4

**Additional context**
A new parameter, actor, would be required to name a trader core after the user that uses bits.
https://vault-hunters.fandom.com/wiki/Trader_Circuit

**Comment by waidesoper** [comment]
Received_bit_donation does already have an actor parameter. I'm looking into the additional drops
